= Часть 1

Метод get() возвращает результат работы Callable.
Выполнение callable должен начинать тот поток, который первый вызвал метод get().
Если несколько потоков одновременно вызывают этот метод, то выполнение должно начаться только в одном потоке,
а остальные должны ожидать конца выполнения (не нагружая процессор).

Если при вызове get() результат уже просчитан, то он должен вернуться сразу,
(даже без задержек на вход в синхронизированную область).

Если при просчете результата произошел Exception, то всем потокам при вызове get(),
надо кидать этот Exception, обернутый в RuntimeException.

== Часть 2

Реализовать интерфейс ExecutionManager.

Метод execute принимает массив тасков, это задания, которые ExecutionManager должен выполнять параллельно.
После завершения всех тасков должен выполниться callback (ровно 1 раз).

Метод execute – это неблокирующий метод, который сразу возвращает объект Context. Context это интерфейс следующего вида:

Метод getCompletedTaskCount() возвращает количество тасков, которые на текущий момент успешно выполнились.

Метод getFailedTaskCount() возвращает количество тасков, при выполнении которых произошел Exception.

Метод interrupt() отменяет выполнения тасков, которые еще не начали выполняться.

Метод getInterruptedTaskCount() возвращает количество тасков, которые не были выполены из-за отмены (вызовом предыдущего метода).

Метод isFinished() вернет true, если все таски были выполнены или отменены, false в противном случае.

